[package]
name = "tide-tracing"
version = "0.0.2"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
A simple middleware for [`tide`](https://github.com/http-rs/tide) using the [`tracing`](https://github.com/tokio-rs/tracing) crate for logging.
"""
documentation = "https://docs.rs/tide-tracing/"
repository = "https://github.com/ethanboxx/tide-tracing"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.12"
tracing = "0.1"
tracing-futures = "0.2"
async-trait = "0.1"

[dev-dependencies]
async-std = { version = "1.6", features = ["attributes"] }
tracing-subscriber = "0.2.9"
