[package]
name = "tide-tracing"
version = "0.0.1"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = "0.12"
tracing = "0.1"
tracing-futures = "0.2"
async-trait = "0.1"

[dev-dependencies]
async-std = { version = "1.6", features = ["attributes"] }
tracing-subscriber = "0.2.9"
